FROM knu-hydops-local:development
RUN apt-get update -qq && apt-get install -y --no-install-recommends fonts-nanum && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --no-cache-dir nbformat==5.11.1 nbclient==0.11.0 ipykernel==7.3.0 ipywidgets==8.1.9
